import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["monospace"],
      },
      colors: {
        // Stitch / Material Design color tokens
        "surface-container": "#eceef0",
        "tertiary": "#0e1629",
        "surface": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#232b3f",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-container": "#8a92aa",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#d5e3fc",
        "primary-fixed-dim": "#b6c6ef",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "primary-container": "#1a2b4b",
        "on-surface-variant": "#44474e",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#75777f",
        "on-secondary-container": "#57657a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#364768",
        "on-primary-fixed": "#081b3a",
        "tertiary-fixed": "#dae2fd",
        "inverse-primary": "#b6c6ef",
        "secondary-fixed-dim": "#b9c7df",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#131b2e",
        "secondary": "#515f74",
        "on-secondary-fixed": "#0d1c2e",
        "primary": "#031635",
        "on-primary-container": "#8293b8",
        "outline-variant": "#c5c6cf",
        "on-error-container": "#93000a",
        "surface-tint": "#4e5e81",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3a485b",
        "secondary-container": "#d5e3fc",
        // shadcn/radix compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
        md: "8px",
        sm: "6px",
        xs: "4px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
